// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChallengeSideToPlay string

const (
	ChallengeSideToPlayWhite  ChallengeSideToPlay = "white"
	ChallengeSideToPlayBlack  ChallengeSideToPlay = "black"
	ChallengeSideToPlayRandom ChallengeSideToPlay = "random"
)

func (e *ChallengeSideToPlay) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengeSideToPlay(s)
	case string:
		*e = ChallengeSideToPlay(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengeSideToPlay: %T", src)
	}
	return nil
}

type NullChallengeSideToPlay struct {
	ChallengeSideToPlay ChallengeSideToPlay
	Valid               bool // Valid is true if ChallengeSideToPlay is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengeSideToPlay) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengeSideToPlay, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengeSideToPlay.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengeSideToPlay) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengeSideToPlay), nil
}

type ChallengeStatus string

const (
	ChallengeStatusOpen      ChallengeStatus = "open"
	ChallengeStatusMatched   ChallengeStatus = "matched"
	ChallengeStatusSuspended ChallengeStatus = "suspended"
)

func (e *ChallengeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengeStatus(s)
	case string:
		*e = ChallengeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengeStatus: %T", src)
	}
	return nil
}

type NullChallengeStatus struct {
	ChallengeStatus ChallengeStatus
	Valid           bool // Valid is true if ChallengeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengeStatus), nil
}

type ChallengeTimeControl string

const (
	ChallengeTimeControl10   ChallengeTimeControl = "1_0"
	ChallengeTimeControl21   ChallengeTimeControl = "2_1"
	ChallengeTimeControl30   ChallengeTimeControl = "3_0"
	ChallengeTimeControl32   ChallengeTimeControl = "3_2"
	ChallengeTimeControl50   ChallengeTimeControl = "5_0"
	ChallengeTimeControl100  ChallengeTimeControl = "10_0"
	ChallengeTimeControl150  ChallengeTimeControl = "15_0"
	ChallengeTimeControl1510 ChallengeTimeControl = "15_10"
	ChallengeTimeControl300  ChallengeTimeControl = "30_0"
	ChallengeTimeControl6060 ChallengeTimeControl = "60_60"
)

func (e *ChallengeTimeControl) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengeTimeControl(s)
	case string:
		*e = ChallengeTimeControl(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengeTimeControl: %T", src)
	}
	return nil
}

type NullChallengeTimeControl struct {
	ChallengeTimeControl ChallengeTimeControl
	Valid                bool // Valid is true if ChallengeTimeControl is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengeTimeControl) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengeTimeControl, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengeTimeControl.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengeTimeControl) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengeTimeControl), nil
}

type Challenge struct {
	ID          pgtype.UUID
	MatchedWith pgtype.UUID
	CreatedBy   pgtype.UUID
	SideToPlay  ChallengeSideToPlay
	Status      ChallengeStatus
	TimeControl ChallengeTimeControl
	MaxRating   int32
	MinRating   int32
	Rating      int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	MatchedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PasswordHash []byte
	PasswordSalt []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserStat struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	BulletRating        int32
	BlitzRating         int32
	RapidRating         int32
	ClassicalRating     int32
	BulletGamesWon      int32
	BulletGamesLost     int32
	BulletGamesDrawn    int32
	BlitzGamesWon       int32
	BlitzGamesLost      int32
	BlitzGamesDrawn     int32
	RapidGamesWon       int32
	RapidGamesLost      int32
	RapidGamesDrawn     int32
	ClassicalGamesWon   int32
	ClassicalGamesLost  int32
	ClassicalGamesDrawn int32
}
