// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (
                        created_by,
                        side_to_play,
                        time_control,
                        max_rating,
                        min_rating,
                        rating
) VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6
) RETURNING id, matched_with, created_by, side_to_play, status, time_control, max_rating, min_rating, rating, created_at, updated_at, matched_at
`

type CreateChallengeParams struct {
	CreatedBy   pgtype.UUID
	SideToPlay  ChallengeSideToPlay
	TimeControl ChallengeTimeControl
	MaxRating   int32
	MinRating   int32
	Rating      int32
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.CreatedBy,
		arg.SideToPlay,
		arg.TimeControl,
		arg.MaxRating,
		arg.MinRating,
		arg.Rating,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.MatchedWith,
		&i.CreatedBy,
		&i.SideToPlay,
		&i.Status,
		&i.TimeControl,
		&i.MaxRating,
		&i.MinRating,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password_hash,
    password_salt
) VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING id, username, email, password_hash, password_salt, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash []byte
	PasswordSalt []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordSalt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallengeToMatch = `-- name: GetChallengeToMatch :one
SELECT id, matched_with, created_by, side_to_play, status, time_control, max_rating, min_rating, rating, created_at, updated_at, matched_at FROM challenges
WHERE
    side_to_play = $1 AND
    status = 'open' AND
    time_control = $2 AND
    rating <= $3 AND
    rating >= $4 AND
    $5 <= max_rating AND
    $5 >= min_rating
ORDER BY created_at
    FOR NO KEY UPDATE SKIP LOCKED
LIMIT 1
`

type GetChallengeToMatchParams struct {
	SideToPlay  ChallengeSideToPlay
	TimeControl ChallengeTimeControl
	MaxRating   int32
	MinRating   int32
	Rating      int32
}

func (q *Queries) GetChallengeToMatch(ctx context.Context, arg GetChallengeToMatchParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeToMatch,
		arg.SideToPlay,
		arg.TimeControl,
		arg.MaxRating,
		arg.MinRating,
		arg.Rating,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.MatchedWith,
		&i.CreatedBy,
		&i.SideToPlay,
		&i.Status,
		&i.TimeControl,
		&i.MaxRating,
		&i.MinRating,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, password_salt, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, password_hash, password_salt FROM users
WHERE username = $1 LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID
	PasswordHash []byte
	PasswordSalt []byte
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.PasswordSalt)
	return i, err
}
