// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetChallengeToMatch(ctx context.Context, arg GetChallengeToMatchParams) (Challenge, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
}

var _ Querier = (*Queries)(nil)
